
# App default values
CLAIVE_FLASK_SERVER_PORT_DEFAULT='29343'
CLAIVE_REST_SERVER_IP_DEFAULT='localhost'
CLAIVE_REST_SERVER_IP='CLAIVE_REST_SERVER_IP'
CLAIVE_LOG_LEVEL_DEFAULT='info'
CLAIVE_WORK_DIR_DEFAULT='~/.claive'
# App specific os env vars -> .env
CLAIVE_FLASK_LOG_LEVEL='CLAIVE_FLASK_LOG_LEVEL'
CLAIVE_FLASK_SERVER_PORT='CLAIVE_FLASK_SERVER_PORT'
CLAIVE_LOG_LEVEL='CLAIVE_LOG_LEVEL'
CLAIVE_WORK_DIR='CLAIVE_WORK_DIR'
CLAIVE_APP_DIR='CLAIVE_APP_DIR'

LOG_LEVEL_CRITICAL='crititcal'
LOG_LEVEL_FATAL='fatal'
LOG_LEVEL_ERROR='error'
LOG_LEVEL_WARN='warn'
LOG_LEVEL_WARNING='warning'
LOG_LEVEL_INFO='info'
LOG_LEVEL_DEBUG='debug'
LOG_LEVEL_DEFAULT=LOG_LEVEL_INFO

ALLOWED_LOG_LEVELS=[
  LOG_LEVEL_CRITICAL,
  LOG_LEVEL_FATAL,
  LOG_LEVEL_ERROR,
  LOG_LEVEL_WARN,
  LOG_LEVEL_WARNING,
  LOG_LEVEL_INFO,
  LOG_LEVEL_DEBUG]