#!/bin/sh

mkdir -p /dev
mkdir -p /proc
mkdir -p /sys
mkdir -p /run

mount -t proc proc /proc
mount -t sysfs sysfs /sys
mount -t tmpfs tmpfs /run
mount -t devtmpfs devtmpfs /dev

mkdir -p /dev/pts
mount -t devpts devpts /dev/pts

depmod -a
modprobe tdx-guest

mount -t 9p -o trans=virtio guest_config mnt -oversion=9p2000.L

KMS=$(jq -r '.KMS // "contract"' mnt/secret-vm.json)

DOCKER_COMPOSE_HASH=$(sha256sum mnt/docker-compose.yaml | cut -f 1 -d ' ')
ROOTFS_HASH=$(sha256sum /dev/sr0 | cut -f 1 -d ' ')

echo "DOCKER_COMPOSE_HASH=$DOCKER_COMPOSE_HASH"
echo "ROOTFS_HASH=$ROOTFS_HASH"

if [ "$KMS" = "dstack" ]; then
    APPID=$(jq -r '.dstack_app_id // ""' mnt/secret-vm.json)
    dstack-util extend --event compose-hash --payload "$DOCKER_COMPOSE_HASH"
    dstack-util extend --event app-id --payload "$APPID"
    dstack-util extend --event os-image-hash --payload "$ROOTFS_HASH"
    if [ -f mnt/docker-files.tar ]; then
        DOCKER_FILES_HASH=$(sha256sum mnt/docker-files.tar | cut -f 1 -d ' ')
        echo "DOCKER_FILES_HASH=$DOCKER_FILES_HASH"
        dstack-util extend --event docker-files-hash --payload $DOCKER_FILES_HASH
    fi
else 
    attest-tool extendrt 3 $DOCKER_COMPOSE_HASH
    attest-tool extendrt 3 $ROOTFS_HASH

    if [ -f mnt/docker-files.tar ]; then
        DOCKER_FILES_HASH=$(sha256sum mnt/docker-files.tar | cut -f 1 -d ' ')
        echo "DOCKER_FILES_HASH=$DOCKER_FILES_HASH"
        attest-tool extendrt 3 $DOCKER_FILES_HASH
    fi
fi
attest-tool report

mkdir -p /root /lower /upper_work
mount -r -t iso9660 /dev/sr0 /lower
mount -t tmpfs tmpfs /upper_work
mkdir /upper_work/upper /upper_work/work
mount -t overlay overlay -o lowerdir=/lower,upperdir=/upper_work/upper,workdir=/upper_work/work /root

mkdir -p /root/mnt/secure
mkdir -p /root/mnt/secure
mkdir -p /root/mnt/config
mkdir -p /root/dev /root/sys /root/proc /root/run

mount --move /mnt /root/mnt/config
mount --move /sys /root/sys
mount --move /proc /root/proc
mount --move /dev /root/dev
mount --move /run /root/run

exec busybox switch_root /root /usr/sbin/init
