#!/bin/sh

mkdir -p /dev
mkdir -p /proc
mkdir -p /sys
mkdir -p /run

mount -t proc proc /proc
mount -t sysfs sysfs /sys
mount -t tmpfs tmpfs /run
mount -t devtmpfs devtmpfs /dev

mkdir -p /dev/pts
mount -t devpts devpts /dev/pts

depmod -a
modprobe tdx-guest

mount -t 9p -o trans=virtio guest_config mnt -oversion=9p2000.L

DOCKER_COMPOSE_HASH=$(sha256sum mnt/docker-compose.yaml | cut -f 1 -d ' ')
ROOTFS_HASH=$(sha256sum /dev/sr0 | cut -f 1 -d ' ')

echo "DOCKER_COMPOSE_HASH=$DOCKER_COMPOSE_HASH"
echo "ROOTFS_HASH=$ROOTFS_HASH"

attest-tool extendrt 3 $DOCKER_COMPOSE_HASH
attest-tool extendrt 3 $ROOTFS_HASH

if [ -f mnt/docker-files.tar ]; then
    DOCKER_FILES_HASH=$(sha256sum mnt/docker-files.tar | cut -f 1 -d ' ')
    echo "DOCKER_FILES_HASH=$DOCKER_FILES_HASH"
    attest-tool extendrt 3 $DOCKER_FILES_HASH
fi

attest-tool report

mkdir -p /cdrom
mount -t iso9660 /dev/sr0 /cdrom
mount -t tmpfs none /root
cp -r /cdrom/* /root
umount /cdrom

mkdir -p /root/mnt/secure
mkdir -p /root/mnt/config

mount --move /mnt /root/mnt/config
mount --move /sys /root/sys
mount --move /proc /root/proc
mount --move /dev /root/dev
mount --move /run /root/run

exec busybox switch_root /root /usr/sbin/init
